#!/bin/bash
apt-get update

# Ensure Git and Apache2 are installed
puppet resource package git ensure=present
puppet resource package apache2 ensure=present

# Ensure Apache2 service is running
puppet resource service apache2 ensure=running

# Clean up and prepare directory
puppet resource file /testdir/clone ensure=absent force=true
puppet resource file /testdir ensure=directory
puppet resource file /testdir/clone ensure=directory

# Clone the repository using HTTPS (without a token)
cd /testdir/clone
git clone https://github.com/stephaniechansddo/devops_repo.git

# Copy the index.html file to the Apache web root
cp -p /testdir/clone/devops-repo/index.html /var/www/html
